### ISSUE TITLE
Add option to redirect local drives over the connection

### ISSUE THREAD

**Issue by Console** [0xthirteen/SharpRDP#1]
Adding the following line to client.cs will enable drive redirection.

rdpConnection.AdvancedSettings5.RedirectDrives = true;

Would probably be a good thing to have that as an optional flag.

**Comment by 0xthirteen** [comment]
I'm adding an update soon, this will be included.

**Comment by 0xthirteen** [comment]
This has been added to latest version. You were credited in CHANGELOG.
