### ISSUE TITLE
Type or namespace cannot be found

### ISSUE THREAD

**Issue by johnjohnsp1** [0xthirteen/SharpRDP#2]
hello, thanks for sharing the tool, I get this problem once I start building the code:

"C:\temp\SharpRDP\SharpRDP\SharpRDP.sln" (default target) (1) ->
"C:\temp\SharpRDP\SharpRDP\SharpRDP\SharpRDP.csproj" (default target) (2) ->
(CoreCompile target) ->
  Client.cs(8,7): error CS0246: The type or namespace name 'AxMSTSCLib' could not be found (are you missing a using dir
ective or an assembly reference?) [C:\temp\SharpRDP\SharpRDP\SharpRDP\SharpRDP.csproj]
  Client.cs(104,65): error CS0246: The type or namespace name 'IMsTscAxEvents_OnLogonErrorEvent' could not be found (ar
e you missing a using directive or an assembly reference?) [C:\temp\SharpRDP\SharpRDP\SharpRDP\SharpRDP.csproj]
  Client.cs(197,67): error CS0246: The type or namespace name 'IMsTscAxEvents_OnDisconnectedEvent' could not be found (
are you missing a using directive or an assembly reference?) [C:\temp\SharpRDP\SharpRDP\SharpRDP\SharpRDP.csproj]

    64 Warning(s)
    3 Error(s)

using Vstudio2019 command line but either with VStudio2017 I get the same error on Client.cs  at this point:

using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
--> using AxMSTSCLib; <--
using MSTSCLib;

thanks

**Comment by JamesIT** [comment]
Go to "Reference Paths" and add the SharpRDP folder where the DLLs/bin files are present.

**Comment by 0xthirteen** [comment]
I accidentally messed up the hint path in the csproj right before pushing which caused this. If you change line 37 in the csproj from <HintPath>\AxInterop.MSTSCLib.dll</HintPath> to <HintPath>AxInterop.MSTSCLib.dll</HintPath> it will be fine. I'll fix this shortly.

**Comment by johnjohnsp1** [comment]
everything works now thanks for the fix
