### ISSUE TITLE
Compilation Failed: Could not find IMsRdpExtendedSettings or Interop.MSTSCLib

### ISSUE THREAD

**Issue by 3lpsy** [0xthirteen/SharpRDP#6]
I tried compiling SharpRDP on Windows 7 with Visual Studio 2019 and received the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'IMsRdpExtendedSettings' could not be found (are you missing a using directive or an assembly reference?)	SharpRDP	C:\Users\sunny\Projects\SharpRDP\SharpRDP\SharpRDP\Client.cs	62	Active
```

Second Error: 

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS7069	Reference to type 'IMsRdpClientAdvancedSettings8' claims it is defined in 'Interop.MSTSCLib', but it could not be found	SharpRDP	C:\Users\sunny\Projects\SharpRDP\SharpRDP\SharpRDP\Client.cs	68	Active
```

I added the C:\Users\sunny\Projects\SharpRDP\SharpRDP\ to to my Reference Paths. Do I need to take any extra steps to successfully compile SharpRDP?

Commit: f312f89f1dc118851392ca6afe65e1a0188d5732 (latest as of writing)

Any guidance/suggestions would be greatly appreciated. Thanks!

**Comment by 0xthirteen** [comment]
Minimum supported client for IMsRdpExtendedSettings and IMsRdpClientAdvancedSettings8 is Windows 8.

**Comment by 3lpsy** [comment]
Thanks!
